apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelpdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelpdb
  template:
    metadata:
      labels:
        app: yelpdb
    spec:
      containers:
      - name: yelpdb
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "yelpdb"
        - name: POSTGRES_PASSWORD
          value: "yelpdb_secret"
        - name: POSTGRES_DB
          value: "yelpdb"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: yelpdb
spec:
  selector:
    app: yelpdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
