apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-redis
  template:
    metadata:
      labels:
        app: yelp-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-redis
spec:
  selector:
    app: yelp-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
