version: '3.8'

services:
  app1:
    build: .
    container_name: yelp-app1
    env_file:
      - .env
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5  
    ports:
      - 9091:9090
    networks:
      - yelp

  app2:
    build: .
    container_name: yelp-app2
    env_file:
      - .env
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5  
    ports:
      - 9092:9090
    networks:
      - yelp

  app3:
    build: .
    container_name: yelp-app3
    env_file:
      - .env
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5  
    ports:
      - 9093:9090
    networks:
      - yelp

  app4:
    build: .
    container_name: yelp-app4
    env_file:
      - .env
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5  
    ports:
      - 9094:9090
    networks:
      - yelp

  app5:
    build: .
    container_name: yelp-app5
    env_file:
      - .env
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5  
    ports:
      - 9095:9090
    networks:
      - yelp

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - yelp

networks:
  yelp: 
    driver: bridge








# services:
#   app:
#     build: .
#     container_name: yelp
#     env_file:
#       - .env
#     mem_limit: 512m
#     mem_reservation: 256m
#     cpus: 0.5  
#     ports:
#       - 9090:9090
#     networks:
#       - yelp


# networks:
#   yelp: 
#     external: true

